### ISSUE TITLE
Contact request

### ISSUE THREAD

**Issue by mkrsym1** [t4bby/wuthering-waves-linux#2]
Hi. I would like to contact you on behalf of AAT. We have a multitude of questions. Can you please provide some direct contact information (Email / Discord / Matrix / whatever)?

**Comment by t4bby** [comment]
You could contact me through my Discord or Email:
`0xt4bby`
`me@t4bby.dev`

**Comment by mkrsym1** [comment]
Alright, sent a request on Discord
